
import React, { useState, useEffect, useRef } from 'react';
import { Terminal as TerminalIcon, PanelRightOpen } from 'lucide-react';
import { AGENTS, AgentMode, Message, ToolState, Task, AppSettings, VirtualFile } from './types';
import { sendMessageToAgent } from './services/aiService';
import { initializeStartupTracking, completeStartup, reportStartupError, setStartupStatusCallback } from './src/utils/StartupTracker';
import { checkOllamaDependencies } from './src/utils/DependencyChecker';
import { TaskDashboard } from './components/TaskDashboard';
import { SettingsModal } from './components/SettingsModal';
import { IncomingTransmission } from './components/IncomingTransmission';
import { ProjectManager } from './components/ProjectManager';
import { ConfigurationProvider } from './src/services/config/configStore';
import { BootSequence } from './components/BootSequence';
import { MessageList } from './components/MessageList';
import { Sidebar } from './components/Sidebar';
import { Header } from './components/Header';
import { InputArea } from './components/InputArea';
import { RightPanel } from './components/RightPanel';
import { useAgentChat } from './hooks/useAgentChat';
import { useCommandParser } from './hooks/useCommandParser';
import { memoryManager, agentCardManager } from './src/agentic';
import { useAgenticSystems } from './hooks/useAgenticSystems';
import { HITLDialog } from './components/HITLDialog';
import { hitlManager, HITLRequest } from './src/pipelines/HITLManager';
import { toolExecutor } from './src/tools/toolExecutor';

// Helper to cycle enum
const getNextAgent = (current: AgentMode): AgentMode => {
  const agents = Object.values(AgentMode);
  const currentIndex = agents.indexOf(current);
  const nextIndex = (currentIndex + 1) % agents.length;
  return agents[nextIndex];
};

// Initial Virtual Files
const INITIAL_FILES: VirtualFile[] = [
  { name: 'package.json', content: '{\n  "name": "nexus-project",\n  "version": "1.0.0"\n}', language: 'json', status: 'unmodified' },
  { name: 'README.md', content: '# Nexus Project\nGenerated by NexusFlow Agents', language: 'markdown', status: 'unmodified' },
  { name: 'src/index.ts', content: 'console.log("Nexus Core Online");', language: 'typescript', status: 'unmodified' },
];

export default function App() {
  const [activeAgent, setActiveAgent] = useState<AgentMode>(AgentMode.CHAT);
  
  // Global Tasks State
  const [tasks, setTasks] = useState<Task[]>([]);
  const [showTaskDashboard, setShowTaskDashboard] = useState(false);
  
  // Virtual File System State
  const [virtualFiles, setVirtualFiles] = useState<VirtualFile[]>(INITIAL_FILES);
  const [showProjectManager, setShowProjectManager] = useState(false);

  // App Settings
  const [showSettings, setShowSettings] = useState(false);
  const [settings, setSettings] = useState<AppSettings>({
    suggestionLevel: 'medium',
    soundEnabled: true,
    autoScroll: true,
    animations: true,
    chatMode: 'agent',
    aiProvider: 'gemini',
    ollamaUrl: 'http://localhost:11434',
    ollamaGeneralModel: 'llama3',
    ollamaCodingModel: 'llama3'
  });

  // Agentic Systems
  const [agenticState, agenticActions] = useAgenticSystems();

  const [showBootSequence, setShowBootSequence] = useState(true);
  const [rightPanelTab, setRightPanelTab] = useState<'telemetry' | 'tools' | 'github' | 'workflow' | 'graph' | 'eval' | 'rag' | 'adaptive'>('telemetry');
  const [showRightPanel, setShowRightPanel] = useState(true);
  const [showMobileSidebar, setShowMobileSidebar] = useState(false);
  
  // HITL State
  const [pendingHITL, setPendingHITL] = useState<HITLRequest | null>(null);

  // New Session Confirmation
  const [showNewSessionConfirm, setShowNewSessionConfirm] = useState(false);

  // Orchestrator State
  const [transitionTarget, setTransitionTarget] = useState<AgentMode | null>(null);

  // Tool State Management
  const [toolState, setToolState] = useState<ToolState>({
    mcp: { active: false, port: '8080' },
    rag: { active: true, content: [] },
    fetch: { active: false, targetUrl: '' },
    doc: { active: false, files: [] }
  });
  
  const messagesEndRef = useRef<HTMLDivElement>(null);

  // Initialize memory and A2A agents on startup
  useEffect(() => {
    // Initialize memory with project context
    const stats = memoryManager.getStats();
    if (stats.totalEntries === 0) {
      // Add initial project memories
      memoryManager.addMemory({
        type: 'decision',
        content: 'NexusFlow project initialized with default files and settings',
        tags: ['project', 'setup', 'initialization'],
        importance: 'medium',
        metadata: { files: INITIAL_FILES.map(f => f.name) },
        relatedEntries: []
      });
      
      memoryManager.addMemory({
        type: 'preference',
        content: 'Default AI provider: Gemini, Suggestion level: medium',
        tags: ['settings', 'configuration'],
        importance: 'low',
        metadata: {},
        relatedEntries: []
      });
      
      memoryManager.addMemory({
        type: 'learning',
        content: 'Project structure: package.json, README.md, src/index.ts',
        tags: ['files', 'structure'],
        importance: 'medium',
        metadata: {},
        relatedEntries: []
      });
    }
    
    // Register A2A agents on startup
    const existingAgents = agentCardManager.getRegisteredAgents();
    if (existingAgents.length === 0) {
      // Register all NexusFlow agents
      Object.values(AGENTS).forEach(agentDef => {
        agentCardManager.createAgentCard({
          name: agentDef.name,
          description: agentDef.description,
          url: `local://nexusflow/${agentDef.id}`,
          capabilities: [
            { name: agentDef.id.toLowerCase(), description: `${agentDef.name} agent`, inputTypes: ['text'], outputTypes: ['text'], maxConcurrentTasks: 1 },
            { name: 'text-generation', description: 'Generate text responses', inputTypes: ['text'], outputTypes: ['text'], maxConcurrentTasks: 5 }
          ],
          supportedModalities: ['text'],
          version: '1.0.0'
        });
      });
    }
  }, []);

  // Use the new hooks
  const {
    input,
    setInput,
    agentHistories,
    isProcessing,
    pendingSwitch,
    setPendingSwitch,
    handleSendMessage: baseHandleSendMessage,
    deleteMessage,
    undoDelete,
    showUndoToast,
    rerunMessage,
    clearAllMessages
  } = useAgentChat({
    activeAgent,
    toolState,
    settings,
    tasks,
    virtualFiles,
    onTasksUpdate: setTasks,
    onFilesUpdate: (newFiles) => {
      setVirtualFiles(prev => {
        const combined = [...prev];
        newFiles.forEach(nf => {
          const idx = combined.findIndex(f => f.name === nf.name);
          if (idx >= 0) {
            combined[idx] = { ...nf, status: 'modified' };
          } else {
            combined.push(nf);
          }
        });
        return combined;
      });
    }
  });

  const { parseCommand } = useCommandParser({
    activeAgent,
    onSwitchAgent: (targetAgent) => {
      if (targetAgent === activeAgent) return;

      // Start Visual Transition
      setTransitionTarget(targetAgent);
      
      // Delay the actual state switch to show the animation
      setTimeout(() => {
          setActiveAgent(targetAgent);
          setTransitionTarget(null);
      }, 2500);
    },
    onShowTaskDashboard: () => setShowTaskDashboard(true)
  });

  // Wrapper for handleSendMessage that includes command parsing
  const handleSendMessage = async () => {
    if (!input.trim()) return;
    
    // Check if it's a command
    if (input.startsWith('/')) {
      const wasCommand = parseCommand(input);
      if (wasCommand) {
        setInput('');
        return;
      }
    }
    
    // Otherwise send as message
    await baseHandleSendMessage();
  };

  // Handle key down for input
  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSendMessage();
    }
  };

  // Wire HITLManager to ToolExecutor
  useEffect(() => {
    // Set up HITL request handler
    hitlManager.onRequest = (request) => {
      setPendingHITL(request);
    };

    // Wire ToolExecutor approval to HITL
    toolExecutor.setApprovalHandler(async (approvalReq) => {
      const response = await hitlManager.requestApproval(
        approvalReq.toolName,
        'tool-execution',
        `Approve: ${approvalReq.toolName}`,
        `${approvalReq.command}\n\nReason: ${approvalReq.reason}`
      );
      return response.approved ? 'approved' : 'denied';
    });
  }, []);

  // Startup tracking and dependency checks
  useEffect(() => {
    initializeStartupTracking();

    if (settings.aiProvider === 'ollama') {
      checkOllamaDependencies(settings.ollamaUrl, settings.ollamaGeneralModel, settings.ollamaCodingModel)
        .then((result) => {
          if (result.success) {
            completeStartup();
          } else {
            const errorMsg = `Dependency Check Failed: ${result.message}\n\nAction Steps:\n${result.actionSteps.join('\n')}`;
            reportStartupError(errorMsg);
            console.error('Ollama Dependency Check Failed:', result);
          }
        })
        .catch((error) => {
          console.error('Error checking Ollama dependencies:', error);
          reportStartupError('Failed to verify Ollama dependencies. Please check if Ollama is running and models are available.');
        });
    } else {
      setTimeout(completeStartup, 1000);
    }
  }, [settings.aiProvider, settings.ollamaUrl, settings.ollamaGeneralModel, settings.ollamaCodingModel]);

  // Boot animation timer
  useEffect(() => {
    const timer = setTimeout(() => setShowBootSequence(false), 2500);
    return () => clearTimeout(timer);
  }, []);

  // Auto scroll
  useEffect(() => {
    if (settings.autoScroll) {
        messagesEndRef.current?.scrollIntoView({ behavior: 'auto', block: 'end' });
    }
  }, [agentHistories, activeAgent, isProcessing, settings.autoScroll]);

  // Keyboard shortcuts
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Tab') {
        e.preventDefault();
        const next = getNextAgent(activeAgent);
        setTransitionTarget(next);
        setTimeout(() => {
          setActiveAgent(next);
          setTransitionTarget(null);
        }, 2500);
      }
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [activeAgent]);

  const handleUpdateTaskStatus = (taskId: string, status: Task['status']) => {
     setTasks(prev => prev.map(t => t.id === taskId ? { ...t, status } : t));
  };

  if (showBootSequence) {
    return <BootSequence />;
  }

  // Derived state for rendering
  const currentMessages = agentHistories[activeAgent];

  return (
    <ConfigurationProvider>
      <div className="h-screen w-screen bg-nexus-900 text-gray-300 font-mono flex flex-col md:flex-row overflow-hidden relative">

        {/* Transition Overlay */}
        {transitionTarget && <IncomingTransmission targetAgent={transitionTarget} />}

        {/* CRT Scanline Effect Overlay */}
        <div className={`absolute inset-0 pointer-events-none z-50 scanline-overlay opacity-20 ${!settings.animations ? 'hidden' : ''}`}></div>
        <div className={`absolute inset-0 pointer-events-none z-50 animate-scanline bg-gradient-to-b from-transparent via-nexus-accent/5 to-transparent h-[10%] ${!settings.animations ? 'hidden' : ''}`}></div>

        {/* Task Dashboard Overlay */}
        {showTaskDashboard && (
           <TaskDashboard
              tasks={tasks}
              onClose={() => setShowTaskDashboard(false)}
              onUpdateStatus={handleUpdateTaskStatus}
           />
        )}

        {/* Project Manager (VSCode Bridge) Overlay */}
        {showProjectManager && (
          <ProjectManager
              onClose={() => setShowProjectManager(false)}
              tasks={tasks}
              agentHistories={agentHistories}
              files={virtualFiles}
              onCommit={(committedFiles) => {
                setVirtualFiles(prev => prev.map(f => 
                  committedFiles.includes(f.name) 
                    ? { ...f, status: 'unmodified' as const }
                    : f
                ));
              }}
              onMerge={() => {
                // Mark all files as unmodified after merge
                setVirtualFiles(prev => prev.map(f => ({ ...f, status: 'unmodified' as const })));
              }}
          />
        )}

        {/* Settings Modal */}
        {showSettings && (
           <SettingsModal
              settings={settings}
              onUpdate={setSettings}
              onClose={() => setShowSettings(false)}
           />
        )}

        {/* HITL Approval Dialog */}
        {pendingHITL && (
          <HITLDialog
            request={pendingHITL}
            onResponded={() => setPendingHITL(null)}
          />
        )}

        {/* Left Sidebar: Agent Grid */}
        <Sidebar
          activeAgent={activeAgent}
          pendingSwitch={pendingSwitch}
          tasks={tasks}
          onSwitchAgent={(targetAgent) => {
            setTransitionTarget(targetAgent);
            setShowMobileSidebar(false);
            setTimeout(() => {
              setActiveAgent(targetAgent);
              setPendingSwitch(null);
              setTransitionTarget(null);
            }, 2500);
          }}
          onDismissPendingSwitch={() => setPendingSwitch(null)}
          onShowTaskDashboard={() => setShowTaskDashboard(true)}
          isOpen={showMobileSidebar}
          onClose={() => setShowMobileSidebar(false)}
        />

        {/* Main Terminal Area */}
        <div className="flex-1 flex flex-col bg-[#0a0a0a] z-10 relative">

          {/* Header Bar */}
          <Header
            activeAgent={activeAgent}
            virtualFiles={virtualFiles}
            onShowSettings={() => setShowSettings(true)}
            onShowProjectManager={() => setShowProjectManager(true)}
            onToggleSidebar={() => setShowMobileSidebar(!showMobileSidebar)}
            onEmergencyStop={() => {
              // Emergency halt all agents
              agenticActions.haltAll();
            }}
            onNewSession={() => {
              setShowNewSessionConfirm(true);
            }}
          />

          {/* Messages Scroll Area */}
          <div className="flex-1 overflow-y-auto p-6 custom-scrollbar relative">
            <div className="max-w-[1000px] mx-auto space-y-6">
            <MessageList
              messages={currentMessages}
              activeAgent={activeAgent}
              isProcessing={isProcessing}
              aiProvider={settings.aiProvider}
              onDeleteMessage={deleteMessage}
              onRerunMessage={rerunMessage}
            />
            <div ref={messagesEndRef} />
            </div>
          </div>

          {/* Input Area */}
          <InputArea
            input={input}
            setInput={setInput}
            activeAgent={activeAgent}
            isProcessing={isProcessing}
            transitionTarget={transitionTarget}
            onKeyDown={handleKeyDown}
            onSendMessage={handleSendMessage}
            settings={settings}
            onSettingsChange={(partial) => setSettings(prev => ({ ...prev, ...partial }))}
            onChatModeChange={(mode) => setSettings(prev => ({ ...prev, chatMode: mode }))}
            onFilesAttached={(files) => {
              // Add attached files to RAG context (one FileReader per file)
              files.forEach(file => {
                if (file.type.startsWith('image/')) {
                  // Images: add metadata reference
                  setToolState(prev => ({
                    ...prev,
                    rag: {
                      ...prev.rag,
                      content: [...prev.rag.content, `FILE: ${file.name} (image, ${(file.size / 1024).toFixed(1)}KB)`],
                      active: true
                    }
                  }));
                } else {
                  // Text files: read content
                  const reader = new FileReader();
                  reader.onload = (e) => {
                    const content = e.target?.result;
                    if (typeof content === "string") {
                      setToolState(prev => ({
                        ...prev,
                        rag: {
                          ...prev.rag,
                          content: [...prev.rag.content, `FILE: ${file.name}\nCONTENT:\n${content}`],
                          active: true
                        }
                      }));
                    }
                  };
                  reader.readAsText(file);
                }
              });
            }}
          />

        </div>

        {/* Right Panel Toggle (when closed) */}
        {!showRightPanel && (
          <button
            onClick={() => setShowRightPanel(true)}
            className="absolute right-0 top-2 z-20 p-1.5 bg-nexus-800 hover:bg-nexus-700 border border-r-0 border-nexus-border rounded-l-md transition-colors text-gray-400 hover:text-nexus-accent"
            title="Expand Panel"
          >
            <PanelRightOpen size={14} />
          </button>
        )}

        {/* Right Panel: Telemetry, Tools & GitHub */}
        <RightPanel
          rightPanelTab={rightPanelTab}
          toolState={toolState}
          settings={settings}
          onSetRightPanelTab={setRightPanelTab}
          onSetToolState={setToolState}
          onUpdateSettings={setSettings}
          isOpen={showRightPanel}
          onToggle={() => setShowRightPanel(false)}
          messages={currentMessages}
          activeAgent={activeAgent}
          isProcessing={isProcessing}
          onAdaptiveAction={(action, agent) => {
            switch (action) {
              case 'Route to specialist':
                // Show notification that routing is available
                console.log(`Routing to specialist from ${agent}`);
                break;
              case 'Create task':
                setShowTaskDashboard(true);
                break;
              case 'View status':
                setRightPanelTab('telemetry');
                break;
              default:
                console.log(`Adaptive action: ${action} from ${agent}`);
            }
          }}
        />

        {/* Undo Delete Toast */}
        {showUndoToast && (
          <div className="fixed bottom-4 left-1/2 -translate-x-1/2 z-50 bg-nexus-800 border border-nexus-border rounded-lg px-4 py-3 shadow-xl flex items-center gap-3 animate-in slide-in-from-bottom-2">
            <span className="text-xs text-gray-300">Message deleted</span>
            <button
              onClick={undoDelete}
              className="text-xs font-bold text-nexus-accent hover:text-white transition-colors px-2 py-1 rounded hover:bg-nexus-700"
            >
              UNDO
            </button>
          </div>
        )}

        {/* New Session Confirmation Dialog */}
        {showNewSessionConfirm && (
          <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm">
            <div className="bg-nexus-900 border border-nexus-border rounded-xl p-6 shadow-2xl w-[400px] animate-in zoom-in-95">
              <h3 className="text-sm font-mono font-bold text-white mb-2">
                NEW SESSION
              </h3>
              <p className="text-xs text-gray-400 mb-6">
                Start a new session? This will clear all messages from all agents. This cannot be undone.
              </p>
              <div className="flex items-center gap-2 justify-end">
                <button
                  onClick={() => setShowNewSessionConfirm(false)}
                  className="px-3 py-1.5 text-xs font-mono text-gray-400 hover:text-white hover:bg-nexus-700 rounded transition-colors"
                >
                  CANCEL
                </button>
                <button
                  onClick={() => {
                    clearAllMessages();
                    setShowNewSessionConfirm(false);
                  }}
                  className="px-3 py-1.5 text-xs font-mono font-bold text-white bg-red-600 hover:bg-red-500 rounded transition-colors"
                >
                  CLEAR ALL
                </button>
              </div>
            </div>
          </div>
        )}

      </div>
    </ConfigurationProvider>
  );
}
